services:
  backend:
    build: ./GoalsApi
    container_name: goalsapp-backend
    image: goals-backend-image
    ports:
      - "8000:8000"
    networks:
      - goals-network
    restart: always  
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./Goals-UI
    container_name: goalsapp-frontend
    image: goals-frontend-image
    ports:
      - "4200:80"
    networks:
      - goals-network
    restart: always
    depends_on:
      - backend

networks:
  goals-network:
    driver: bridge