services:
  goals-backend:
    build: ./GoalsApi
    container_name: goalsapp-backend
    image: goals-backend-image
    restart: unless-stopped
    ports:
      - "7000:8000"
    networks:
      - goals-network
    environment:
      - PYTHONUNBUFFERED=1

  goals-frontend:
    build: ./Goals-UI
    container_name: goalsapp-frontend
    image: goals-frontend-image
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - goals-network
    depends_on:
      - goals-backend

networks:
  goals-network:
    driver: bridge