export const PriorityConstant: number[] = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,
36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53];

export const ProjConstant: string[] = ["ADMN", "AGE", "AOP", "AVL", "BOM", "CCC", "COMM", "COST", "ENG",
     "FAB", "FIN", "FUND", "GEN", "GM47", "HR", "INST", "IT", "OPEX", "PURC", "QUAL", "RCCA", 
     "SALES", "SOX", "TJRS"];
export const VPContant: string[] = ["JVA","MRA","KLA","KAA","EFA","CJA","SGA","BSA","MXA"]
export const WHOConstant: string[] = ["JVA","MRA","KLA","KAA","EFA","CJA","SGA","BSA","MXA",
    "SFA","JLA","JMA","MMA","AMA","UMA","JPA","JRA","CBA","JTA","HSA","HBA","RPA","SAA","ANA",
    "JNA","LMA","SMA","AVA","AGA","JIA","WJA","BAA","JDA","ETA","ACA","AJA","AZA","NEA","HDA",
    "JGA","CHA","RSA","ATA","MEA","EXA","TFA","AXA","ASA","AYA","GXA","KMA","JXA","JSA","JUA",
    "NXA","AWA","ADA","JWA","RLA","EZA","JOA","LXA","JJB","RAB","JHB","DAB","IFB","KSB","JKB",
    "RZB","JTB","DCB","CZB","GXB","TAB","JKL","KYB","GFB","ETB","JRB","JZB","JYB","STB","JBB",
    "GGB","MMB","HSB","JGB","JEB","JIB","YXB","IAB","BKB","SSB","JVB","TSB","AZB","MCB","PAB",
    "MYB","DWB","EPB","TZB","RMB","JCB","JWB","MAB","AJB","CAB","HDB","MLB","MSB","EDB","WRB",
    "RJB","KBB","TJB","JPB","JLB","MXB","BRB","JMB","JXB","MDB","MOB","JAB","OJB","ACB","DMB",
    "DZB","TXB","LBB","KLB","JQB","KXB","TRB","MEB","BBB","NJB","BJB","EZB","SCB","SXB","ERB",
    "HIB","SYB","NKB","TNB","RXB","JNB","JFB","KZB","EXB","JSB","CXB","RYB","MZB","NXB","MBB",
    "ELB","CLB","JDB","ZSB","JXC","MAC","MZC","JJC","RJC","TNC","GMC","JWC","JAC","AXC","CEC",
    "SDC","JMC","CXC","VVC","NSC","JIC","JFC","ASC","MWC","RSC","MXC","JDC","TMC","BXC","LXC",
    "OXC","LHC","JZC","SPC","MYC","DBC","PTC","JYC","DAC","MEC","REC","THC","EJC","BJC","DRC",
    "CVC","JUC","TXC","AEC","NXC","CYC","OYC","EXC","ADC","JSC","ETC","CC","DXC","JGC","VXC",
    "SAC","LEC","LVC","TLC","RZC","EPC","MTC","BFC","EOC","JEC","BCC","CZC","GEC","MRC","JPC",
    "VAC","KAC","MJC","WXC","OZC","SZC","MMC","JTC","AFC","JBC","PCC","BRD","BDD","ADD","RXD",
    "KDD","QBD","EKD","JBD","ESD","EHD","JTD","NXD","BCD","JAD","HRD","IPD","CZD","AND","JSD",
    "GMD","CBD","JGD","AZD","CLD","DAD","DXD","TBD","LDJ","LSD","RJD","BSD","DRD","MDW","SXD",
    "MLD","ODD","JZD","AXD","SPD","MMD","ECD","IED","JMD","JRD","RFD","EJD","DLD","KGD","NMD",
    "LMD","MAD","DSD","AMD","DKD","MXD","MDD","SWD","EXD","JWD","DCD","EWD","TZD","DHE","BME",
    "KXE","SNE","NRE","SBE","DME","TXE","IJE","NJE","RCE","MEE","ADE","MJE","MVE","SLE","WDE",
    "JKE","EXE","KPE","RGE","EJE","PXF","LAF","CSF","JTF","JMF","AJF","CRF","TCF","SMF","MDF",
    "TMF","KMF","CZF","NWF","FRF","JDF","AMF","KFF","JGF","DPF","DJF","BAF","RNF","MEF","GOF",
    "DZF","JF","PDF","BGF","KCF","CKF","BJF","PSF","JQG","BJG","GXG","BVG","GZG","IPG","JGG",
    "MWG","MAG","PTG","RYG","CXG","RBG","KXG","SEG","SXG","TXG","NFG","ECG","JYG","PXG","ASG",
    "EYG","JDG","MZG","RZG","DJG","DYG","RXG","BYG","EAG","RLG","JXG","TZG","DLG","RDG","CZG",
    "BZG","KAG","AYG","MBG","GGG","NXG","DAG","RJG","SPG","CCG","VMG","WXG","ADG","REG","SCG",
    "EEG","EKG","RLH","HKH","BWH","AXH","AYH","EMH","MGH","RCH","MYH","RDH","SYH","SAH","MXH",
    "JDH","DJH","HBH","CJH","JAH","JRH","MVH","KLH","MWH","KMH","ATH","SZH","ARH","OJH","MJH",
    "GBH","KXH","LRH","SOH","JNH","ZMH","AZH","ADH","CDH","DXH","ERH","IVH","JJH","LXH","RIH",
    "TRH","CBH","KZH","CZH","IXH","HZH","KNH","SGH","JWH","MCH","BRH","JUH","AVH","JTH","TMH",
    "GZH","AAH","LNH","MZH","MAH","JYH","SDH","CAH","GYH","AXI","JCI","CXI","SDI","MWI","MSI",
    "GLI","CAI","SGJ","ERJ","JXJ","ILJ","YMJ","RLJ","CJJ","GGJ","MWJ","IEJ","VAJ","MBJ","KBJ",
    "BSJ","JHJ","PXJ","AJJ","CDJ","JWJ","JTJ","MHJ","MAJ","NSJ","TCJ","GMJ","CSJ","CYJ","SHJ",
    "CLJ","KMJ","NMJ","NJJ","PZJ","JBJ","KXJ","CXJ","GLJ","JXK","KXK","CMK","JHK","GEK","BXK",
    "KLK","DWK","IAK","TKK","MKK","WXK","JMK","JAK","ERK","EDK","WZK","LXK","RCL","JLO","SBL",
    "CRL","JML","EAL","HXL","DXL","LUL","LSL","LXL","MVL","GXL","RYL","ACL","BZL","DZL","CLL",
    "JAL","ML","WXL","QLL","WZL","YJL","RML","JYL","AML","DDL","ODL","KRL","MSL","MXL","WBL",
    "CFL","ASL","RXL","JDL","AYL","NML","PML","MZL","RAL","EXL","CEL","MYL","DCL","CJL","TJL",
    "RZL","AXL","HYL","HZL","BAL","CAL","ZLL","MGL","NNL","JXL","ABM","CCM","GJM","DUM","LWM",
    "DMM","SMD","KZM","DEM","EMM","MOM","RZM","LVM","AZM","QLM","IRM","EDM","EAM","CGM","MRM",
    "VFM","MMM","SPM","AVM","SMM","RYM","RCM","ZPM","AYM","LMM","AXM","CMP","EYM","MJM","KOM",
    "GAM","VXM","ALM","JJM","ECM","COM","JIM","RAM","NXM","CYM","JYM","PMM","BZM","AIM","BVM",
    "MEM","RXM","MZM","DWM","SEM","SZM","LCM","TJM","DAM","TYM","DZM","SAM","DLM","JRM","JMM",
    "HMM","LXM","MSM","ARM","CXZM","LRM","MQM","MTM","SHM","MCM","MLM","JZM","KAM","RDM","TXM",
    "IAM","RJM","EOM","JXM","TMM","TZM","TGM","EWM","AWM","EVM","CEM","KMM","SDM","VMM","RMM",
    "VCM","VYM","DNM","DBM","EZM","ACM","KYM","CZM","MPM","APM","TAM","LYM","MXM","BJM","DXM",
    "HXM","BXM","HNM","ANM","EXM","DRM","JXN","JMN","JAN","CPN","PAN","ENN","GWN","BFN","TXN",
    "JTN","JZN","BDN","JKN","CTN","MJN","MSN","IBN","MXN","KXN","JLN","CNN","JDN","GCN","RXN",
    "MCO","CGO","MMO","XAO","AXO","GSO","MIO","CMO","MTO","PXO","DMO","EJO","CPO","REO","AZO",
    "CRO","JCO","SLO","RAO","AWO","OGO","JAP","DCP","ZTP","CAP","JVP","EWP","MRP","MYP","AWP",
    "JTP","HXP","MTP","AUP","JBP","ABP","SMP","GWP","ATP","SXP","RXP","DJP","DXP","AXP","JZP",
    "AEP","MAP","LAP","LFP","AMP","JRP","KFP","ZXP","RZP","CYP","GYP","KEP","TSP","KAP","JWP",
    "CXP","JSP","CSP","GZP","LDP","CWP","MZP","JJP","AYP","KBP","MXP","GXP","LXP","TJP","RJP",
    "HLP","RVP","BTP","EXP","AZP","PYP","WTP","JAQ","JRQ","VXR","AVR","HCR","RRR","AYR","GLR",
    "JOR","MZR","TWR","ISR","BDR","BRR","DKR","ACR","TLR","TCR","MPR","BMR","MSR","JMR","DCR",
    "KZR","JAR","MMR","BWR","LZR","DZR","CCR","LKR","SAR","EXR","AZR","LMR","JPR","MAR","ZXR",
    "TTR","AXR","DGR","DPR","KDR","ATR","ALR","KSR","IBR","MIR","JCR","TSR","GCR","MXR","JZR",
    "AAR","KAR","GRS","JCS","AIS","DCS","BDS","AVS","JVS","MFS","DLS","JYS","JRS","MDS","LPS",
    "CXS","KXS","AYS","DRS","TSS","JUS","WAS","JES","MJS","EPS","MWS","SZS","AK","IXS","MYS",
    "NAS","KAS","DXS","MZS","GJS","JWS","DOS","JXS","NLS","DAS","CWS","GCS","JBS","LXS","MAS",
    "NXS","PXS","SLS","RMS","DBS","ZTS","CKS","KJS","BWS","CZS","SNS","RAS","SAS","JSS","EUS",
    "ASO","BXS","JAS","VAS","JMS","IZS","NFS","JDS","JZS","DZS","TKS","RXS","SCS","KZS","RZS",
    "BZS","JTS","HCS","VNS","JPS","MXS","ROS","EXS","DYS","CLS","CMS","DXT","SRT","MRT","DVT",
    "RET","RMT","JJT","CBT","AJT","CST","KMT","SWT","CTT","CCT","CZT","LMT","BET","KXT","MET",
    "AZT","EXT","THT","TGT","WJT","SST","GKT","JZT","DZT","DGT","TJR","DYT","MMT","JFT","CXT",
    "DDT","KLT","JXT","RXT","JRT","MQT","RZT","BRT","JCU","ABU","CXU","JPV","CXV","AZV","JZV",
    "JDV","JFV","DXV","DJV","RXV","JMV","VZV","RAV","RZV","PMV","JYV","CLV","HAV","GMV","RMV",
    "AXV","EVV","JSV","PPV","ARV","WPV","JBW","LBW","DCW","TCW","LXW","DXW","ACW","TZW","NTW",
    "ALW","TYW","TXW","JZW","ZJW","HXW","SBW","JMW","CSW","TLW","AMW","JRW","ZPW","ZXW","SJW",
    "SDW","BEW","MJW","CEW","DZW","GXW","MZW","MAW","NMW","NXW","RLW","JAW","AXW","JYW","NBW",
    "KMW","SXW","BMW","TJW","GZW","RHW","JXW","RXW","TAW","CMY","GAY","JGY","WY","ZXY","AZY",
    "BSY","MRY","DXY","AXY","CXZ","AKZ","JXZ","ZXZ","FDZ","MCZ"]

    export const statuslist = ["N","C","ND","CD","R","K"]