export const PriorityConstant: number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
    16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
    36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53];

export const EdConstant: string[] = ["", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53"];

export const ProjConstant: string[] = ["ADMN", "AGE", "AOP", "AVL", "BOM", "CCC", "COMM", "COST", "ENG",
    "FAB", "FIN", "FUND", "GEN", "GM47", "HR", "INST", "IT", "OPEX", "PURC", "QUAL", "RCCA",
    "SALES", "SOX", "TJRS"];
export const VPContant: string[] = ["VNS", "JVA", "MRA", "KLA", "KAA", "EFA", "CJA", "SGA", "BSA", "MXA"]
export const WHOConstant: string[] = ["JVA", "KLA", "KAA", "EFA", "CJA", "SGA", "BSA", "MXA", "SFA",
    "AMA", "UMA", "JPA", "JRA", "CBA", "JTA", "HSA", "RPA", "SAA", "LMA", "AGA", "JIA", "WJA",
    "BAA", "JDA", "ETA", "ACA", "AJA", "AZA", "NEA", "HDA", "JGA", "CHA", "RSA", "ATA", "MEA",
    "EXA", "TFA", "AXA", "GXA", "JMA", "JSA", "JUA", "NXA", "AWA", "ADA", "JWA", "RLA", "EZA",
    "JOA", "LXA", "JJB", "RAB", "JHB", "DAB", "IFB", "JKB", "JTB", "CZB", "GXB", "TAB", "KYB",
    "GFB", "ETB", "JRB", "JZB", "STB", "GGB", "MFB", "YXB", "IAB", "CJB", "BKB", "SSB", "TSB",
    "MCB", "MYB", "EPB", "RMB", "JCB", "MAB", "AJB", "MMB", "CAB", "HDB", "MLB", "EDB", "WRB",
    "RJB", "TJB", "JPB", "JLB", "MXB", "BRB", "JMB", "JXB", "MDB", "POB", "JAB", "OJB", "ACB",
    "DMB", "TXB", "LBB", "JQB", "KXB", "TRB", "MEB", "BBB", "NJB", "BJB", "EZB", "SXB", "ERB",
    "HIB", "SYB", "NKB", "TNB", "RXB", "JNB", "JFB", "KZB", "EXB", "JSB", "CXB", "RYB", "MZB",
    "MBB", "ELB", "CLB", "JDB", "ZSB", "JXC", "MAC", "MZC", "RJC", "TNC", "GMC", "JWC", "JAC",
    "AXC", "CEC", "JMC", "CXC", "VVC", "NSC", "JIC", "JFC", "ASC", "MWC", "RSC", "MXC", "JDC",
    "TMC", "BXC", "LXC", "OXC", "LHC", "JZC", "SPC", "MYC", "PAC", "JYC", "DAC", "MEC", "REC",
    "THC", "EJC", "BJC", "DRC", "CVC", "JUC", "TXC", "AEC", "NXC", "CYC", "OYC", "EXC", "ETC",
    "CC", "JGC", "VXC", "SAC", "LVC", "RZC", "EPC", "MTC", "BFC", "EOC", "JEC", "BCC", "CZC",
    "CRC", "JPC", "IAC", "VAC", "MJC", "WXC", "OZC", "SZC", "JTC", "AFC", "JBC", "PCC", "BRD",
    "BDD", "ADD", "KDD", "QBD", "EKD", "JBD", "ESD", "EHD", "JTD", "NXD", "BCD", "JAD", "HRD",
    "IPD", "GMD", "JGD", "AZD", "DAD", "LDJ", "LSD", "RJD", "DRD", "MDW", "SXD", "MLD", "ODD",
    "JZD", "AXD", "MMD", "ECD", "IED", "JMD", "JRD", "RFD", "EJD", "NMD", "LMD", "MAD", "DSD",
    "DKD", "MXD", "MDD", "SWD", "EXD", "JWD", "EWD", "DHE", "KEE", "BDE", "DME", "TXE", "NJE",
    "RCE", "MEE", "MJE", "MVE", "SLE", "WDE", "JKE", "EXE", "KPE", "RGE", "EJE", "PXF", "CSF",
    "JTF", "JMF", "AJF", "CRF", "TCF", "SMF", "MDF", "TMF", "KMF", "CZF", "NWF", "JLF", "AMF",
    "BXF", "KFF", "JGF", "DPF", "DJF", "BAF", "RNF", "MEF", "DZF", "JF", "PDF", "CKF", "PSF",
    "JQG", "BJG", "GXG", "BVG", "GZG", "IPG", "JGG", "MWG", "MAG", "PTG", "CXG", "RBG", "KXG",
    "SEG", "SXG", "TXG", "NFG", "ECG", "JYG", "PXG", "ASG", "EYG", "JDG", "MZG", "RZG", "DJG",
    "DYG", "RXG", "BYG", "EAG", "RLG", "MXG", "TZG", "DLG", "RDG", "CZG", "BZG", "KAG", "AYG",
    "MBG", "GGG", "DAG", "RJG", "SPG", "CCG", "VMG", "WXG", "ADG", "SCG", "EEG", "HKH", "BWH",
    "AXH", "EMH", "MGH", "RCH", "SYH", "SAH", "JDH", "HBH", "CJH", "JAH", "JRH", "MVH", "KLH",
    "MWH", "KMH", "ATH", "SZH", "RMH", "ARH", "OJH", "MJH", "GBH", "LRH", "SOH", "JNH", "ZMH",
    "AZH", "ADH", "CDH", "DXH", "ERH", "IVH", "JJH", "RIH", "TRH", "CBH", "KZH", "CZH", "IXH",
    "HZH", "KNH", "SGH", "JWH", "MCH", "BRH", "JUH", "AVH", "JTH", "TMH", "GZH", "AAH", "LNH",
    "MZH", "MAH", "SDH", "CAH", "AXI", "JCI", "SDI", "MWI", "GLI", "CAI", "SGJ", "ERJ", "JXJ",
    "JYJ", "ILJ", "YMJ", "RLJ", "CJJ", "GGJ", "MWJ", "IEJ", "VAJ", "MBJ", "KBJ", "JHJ", "PXJ",
    "AJJ", "CDJ", "JWJ", "JTJ", "MHJ", "MAJ", "NSJ", "TCJ", "GMJ", "CSJ", "KJJ", "SHJ", "CLJ",
    "KMJ", "NMJ", "NJJ", "PZJ", "JBJ", "KXJ", "CXJ", "GLJ", "JXK", "KXK", "CMK", "JHK", "GEK",
    "KLK", "DWK", "IAK", "MKK", "WXK", "JMK", "JAK", "ERK", "EDK", "WZK", "LXK", "RCL", "JLO",
    "CRL", "JML", "HAL", "HXL", "DXL", "LUL", "LSL", "LLL", "MVL", "GXL", "RYL", "ACL", "BZL",
    "DZL", "CLL", "JAL", "ML", "QLL", "WZL", "YJL", "RML", "JYL", "AML", "DDL", "ODL", "KRL",
    "MSL", "MXL", "WBL", "CFL", "ASL", "RXL", "JDL", "JZL", "AYL", "MZL", "RAL", "EXL", "CEL",
    "MYL", "DCL", "CJL", "JTL", "RZL", "AXL", "HYL", "HZL", "CAL", "MGL", "NNL", "JXL", "ABM",
    "CCM", "GJM", "LWM", "DMM", "SMD", "KZM", "EMM", "MOM", "RZM", "LVM", "AZM", "QLM", "IRM",
    "EDM", "EAM", "CGM", "MRM", "VFM", "MMM", "SPM", "AVM", "SMM", "RYM", "RCM", "ZPM", "AYM",
    "LMM", "AXM", "CMP", "EYM", "MJM", "KOM", "GAM", "VXM", "ALM", "JJM", "ECM", "COM", "JIM",
    "RAM", "NXM", "CYM", "JYM", "DYM", "PMM", "BZM", "AIM", "MEM", "RXM", "MZM", "DWM", "SEM",
    "SZM", "LCM", "DAM", "DZM", "SAM", "DLM", "JRM", "JMM", "LXM", "MSM", "ARM", "CXZM", "LRM",
    "SHM", "MCM", "SJM", "MLM", "JZM", "KAM", "RDM", "TXM", "RJM", "EOM", "JXM", "TMM", "TZM",
    "TGM", "EWM", "AWM", "EVM", "CEM", "KMM", "SDM", "VMM", "RMM", "VCM", "VYM", "DNM", "DBM",
    "EZM", "KYM", "ATM", "CZM", "MPM", "APM", "TAM", "LYM", "MXM", "THM", "BJM", "DXM", "HXM",
    "BXM", "DCM", "HNM", "ANM", "EXM", "DRM", "JXN", "JMN", "JAN", "CPN", "PAN", "ENN", "GWN",
    "BFN", "TXN", "JTN", "JZN", "BDN", "JKN", "CTN", "MJN", "JRN", "MSN", "MXN", "KXN", "JLN",
    "CNN", "GCN", "RXN", "MCO", "CGO", "MMO", "XAO", "GSO", "MIO", "CMO", "MTO", "PXO", "DMO",
    "EJO", "REO", "CRO", "JCO", "SLO", "RAO", "AWO", "OGO", "BMP", "JAP", "DCP", "ZTP", "CAP",
    "EWP", "MRP", "MYP", "AWP", "JTP", "HXP", "CTP", "AUP", "JBP", "SMP", "GWP", "ATP", "SXP",
    "RXP", "AXP", "JZP", "AEP", "MAP", "LAP", "LFP", "JRP", "KFP", "ZXP", "RZP", "CYP", "GYP",
    "KEP", "TSP", "KAP", "JWP", "CXP", "DTP", "JSP", "GZP", "LDP", "CWP", "MZP", "JJP", "AYP",
    "KBP", "MXP", "GXP", "LXP", "TJP", "RJP", "HLP", "BTP", "EXP", "AZP", "PYP", "WTP", "JAQ",
    "JRQ", "VXR", "AVR", "HCR", "RRR", "AYR", "GLR", "JOR", "MZR", "TWR", "BDR", "BRR", "DKR",
    "ACR", "TLR", "TCR", "MPR", "BMR", "JMR", "DCR", "JAR", "MMR", "LZR", "DZR", "CCR", "LKR",
    "SAR", "EXR", "AZR", "LMR", "JPR", "SSR", "MAR", "ZXR", "TTR", "AXR", "TJR", "DGR", "DPR",
    "KDR", "ATR", "ALR", "KSR", "IBR", "MIR", "JCR", "TSR", "GCR", "MXR", "JZR", "AAR", "KAR",
    "GRS", "JCS", "AIS", "DCS", "AVS", "MFS", "DLS", "JYS", "MDS", "LPS", "CXS", "KXS", "AYS",
    "TSS", "JUS", "WAS", "JES", "MJS", "EPS", "MWS", "SZS", "AK", "IXS", "SFS", "KAS", "DXS",
    "MZS", "GJS", "JWS", "DOS", "JXS", "NLS", "DAS", "CWS", "GCS", "JBS", "LXS", "MAS", "PXS",
    "SLS", "RMS", "TAS", "DBS", "ZTS", "KJS", "BWS", "CZS", "SNS", "RAS", "SAS", "JSS", "EUS",
    "ASO", "VAS", "IZS", "JDS", "DZS", "TKS", "RXS", "KZS", "RZS", "BZS", "JTS", "HCS", "VNS",
    "JPS", "MXS", "ROS", "EXS", "DYS", "CLS", "CMS", "DXT", "SRT", "DVT", "RET", "RMT", "CBT",
    "CST", "KMT", "SWT", "CTT", "CCT", "CZT", "LMT", "BET", "KXT", "MET", "AZT", "EXT", "TGT",
    "WJT", "SST", "GKT", "JYT", "DGT", "DYT", "JFT", "CXT", "DDT", "JTG", "KLT", "JXT", "RXT",
    "MQT", "RZT", "BRT", "JCU", "ABU", "JPV", "CXV", "AZV", "JDV", "JFV", "DXV", "DJV", "RXV",
    "JMV", "VZV", "RAV", "PMV", "JYV", "HAV", "GMV", "RMV", "AXV", "EVV", "JSV", "PPV", "ARV",
    "WPV", "JBW", "LBW", "DCW", "TCW", "DXW", "ACW", "TZW", "NTW", "TXW", "JZW", "ZJW", "HXW",
    "SBW", "JMW", "CSW", "TLW", "AMW", "JRW", "ZPW", "ZXW", "SDW", "BEW", "MJW", "CEW", "DZW",
    "GXW", "MZW", "MAW", "NXW", "RLW", "AOW", "JAW", "JSW", "NBW", "KMW", "SXW", "BMW", "TJW",
    "GZW", "RHW", "RXW", "TAW", "CMY", "GAY", "JGY", "WY", "ZXY", "AZY", "BSY", "DXY", "AXY",
    "CXZ", "AKZ", "JXZ", "ZXZ", "FDZ", "MCZ"]

export const statuslist = ["N", "C", "ND", "CD", "R", "K", "D"]